### ISSUE TITLE
Feature Request:  An example using React and testing-library/react

### ISSUE THREAD

**Issue by king612** [amiceli/vitest-cucumber-example#1]
I'm trying to use this on a large React project with an extensive set of legacy Jest-based cucumber-style tests.  We want to use Vites purely and remove all the Jest stuff.   Is there an example of this anywhere using your project?

This project looks very promising.  Thanks for all the work on this.  Great job!

**Comment by amiceli** [comment]
Hi, thank you for your message.
For React we talked about it on this vitest-cucumber [issue](https://github.com/amiceli/vitest-cucumber/issues/79).

Currently I don't have an example of vitest-cucumber with React.
I never coded with React ^^.
I can try to make an example but won't be a real projet ;).

**Comment by charlieforward9** [comment]
Hey @king612, see https://github.com/amiceli/vitest-cucumber/issues/79#issuecomment-2457259652

**Comment by amiceli** [comment]
Thanks @charlieforward9  ;)
@king612 I can close this issue, you can check [vitest-cucumber_rtl_template](https://github.com/Agriculture-Intelligence/vitest-cucumber_rtl_template).

Is a `React` project template using vitest-cucumber
